### ISSUE TITLE
[BUG] modules/analysis/aws-batch-demo/modulestack.yaml too permissive

### ISSUE THREAD

**Issue by chamcca** [awslabs/autonomous-driving-data-framework#22]
The `modules/analysis/aws-batch-demo/modulestack.yaml` contains the following permissions which should be addressed:
```
          - Action:
              - "secretsmanager:Get*"
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:ListSecretVersionIds"
              - "kms:Decrypt*"
            Effect: Allow
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*"
```

- the `kms:Decrypt` action has to effect as there isn't a KMS Resource specified.
- the Resource for secretsmanager doesn't follow least privilege best practices and should be scoped to an addf-prefixed secret or specific secret.
